### ISSUE TITLE
export-charas: error: the following arguments are required: chara_mapping

### ISSUE THREAD

**Issue by JacondaMarsi** [dogtopus/gachalifebeta10-tool#1]
Hi! 
when i start python gachalifebeta10_tool.py gachalifebeta10.sol export-charas
i got error: 

> usage: gachalifebeta10_tool.py savefile export-charas [-h] chara_mapping [chara_mapping ...]
> gachalifebeta10_tool.py savefile export-charas: error: the following arguments are required: chara_mapping
``

can you help me?

**Comment by dogtopus** [comment]
You should also specify which slots to export by adding `<slot id>:<filename>`. e.g. `1:chara1.json` exports the character in slot 1 to a file named `chara1.json`. Import works the same way except that the character data in the files you specified gets imported to the specified slots.

Also for Gacha Club, slot #11-100 are mapped to extra slots #1-90.
